services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000"
    environment:
      - VM_I=20.244.4.80
    restart: unless-stopped
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_ADDR=http://20.244.4.80:8000
      - VM_I=20.244.4.80
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
